### ISSUE TITLE
Current usability status?

### ISSUE THREAD

**Issue by FrankTCA** [4194304/fluorine-desktop#2]
Just looking into this project. May want to test it out, and if I like it I'd like to make this project a lot more popular.

Mike already signed you up for my Matrix/Element homeserver. Send me a DM @frank

**Comment by 4194304** [comment]
I have sent you a DM. My account has existed for as long as the time that Mike switched to Element, and I created it.

For the project, Fluorine can be daily driven at this point. At this current place in time, I am no longer making extreme changes to how the desktop itself is structured and functions, and it isn't an unstable mess bound to one machine. Be prepared to use the terminal, and deal with potential problems. I'd say it's likely in "beta", as I am still figuring out how certain elements of the desktop will work, and what I want to be added, and that support outside of Arch is a bit spotty.

Fluorine is __built__ to run on Arch. Fluorine is __made__ on Arch as well, so if you're using a distribution such as Ubuntu or Debian, look further into the README and see if the packages are listed. If you have a package manager that __isn't__ there, you'll have to manually search for the packages.

So what you should know: Fluorine is pretty stable but a few breaking changes could be thrown in at any time, the desktop will likely remain in its structure from this point onward, be prepared to use the terminal, and deal with potential problems as well.

**Comment by 4194304** [comment]
This is kinda off topic and not exactly a real issue anymore so I'm closing this.
